In [1]:
import re
import pandas as pd

In [2]:
pattern = 'https://www.cnn.com/\d{4}/\d{2}/\d{2}/(?P<word>\w+)/'
result = re.match(pattern, url)

NameError: name 'url' is not defined

In [35]:
url1 = 'https://www.cnn.com/2021/01/21/politics/border-wall-joe-biden-defense-department/index.html'
url2 = 'https://www.cnn.com/style/article/michelle-obama-inauguration-outfit/index.html'
url3 = 'https://money.cnn.com/2021/01/22/app-news-section/videos-of-the-week-mobile-january-22/index.html'

In [23]:
pattern2 = 'https://www.cnn.com/(?P<word>[a-z]*)/'
result = re.match(pattern2, url)
result.group('word')

'style'

In [36]:
def get_topic(url):
    pattern = 'http(s)?://(www|money).cnn.com/\d{4}/\d{2}/\d{2}/(?P<topic>[a-z0-9-]+)/'
    result = re.match(pattern, url)
    topic = None
    if result:
        topic = result.group('topic')
    if not result:
        pattern2 = 'https://www.cnn.com/(?P<topic>[a-z]*)/'
        result = re.match(pattern2, url)
        if result:
            topic = result.group('topic')
    if topic:
        return topic
    else:
        return ''

In [26]:
pattern = 'http(s)://www.cnn.com/\d{4}/\d{2}/\d{2}/(?P<topic>)/'
result = re.match(pattern, url)
result

In [38]:
get_topic(url1)

'politics'

In [39]:
get_topic(url2)

'style'

In [40]:
get_topic(url3)

'app-news-section'

In [30]:
article_user_data = 'data/article_user.csv'
article_user = pd.read_csv(article_user_data)
articles_data = 'data/articles.csv'
articles = pd.read_csv(articles_data)

In [31]:
articles['topic'] = articles.apply(lambda r: get_topic(r['url']), axis=1)

In [32]:
articles.to_csv('with_topics.csv')

In [253]:
# check if user exists
# if note then recommend from cold start model

from sklearn.linear_model import LogisticRegression

In [254]:
from sklearn.preprocessing import OneHotEncoder

In [255]:
# pd.get_dummies(articles)
pd.get_dummies(articles['topic'])

,africa,americas,app-news-section,asia,business,business-india,cars,china,cnn10,economy,...,sport,style,success,tech,tennis,travel,uk,us,weather,world
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1451,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [256]:
LogisticRegression()

LogisticRegression()

In [257]:
len(article_user['article_id'].unique())

1455

In [258]:
from sklearn.model_selection import train_test_split

In [259]:
article_user

,user_id,article_id,timestamp
0,2bc424123e0a12d29c488bb6e565fe98d0a49b46,e9d06b2bb42bd9970de43beab2d3893534d7a619,1611291180
1,2bc424123e0a12d29c488bb6e565fe98d0a49b46,e98b0d02b16794bc0884a61c4a45746cb9430630,1611290464
2,2bc424123e0a12d29c488bb6e565fe98d0a49b46,05f51c586ada891448ab56d9a5c8adb2a688e2fb,1611406104
3,2bc424123e0a12d29c488bb6e565fe98d0a49b46,91333a3c6d28c9241cbb01678a97699232b79e70,1611531797
4,2bc424123e0a12d29c488bb6e565fe98d0a49b46,30170d08779c54b84170d4cb3b5cbe0462df704a,1611270926
...,...,...,...
520225,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,77e2fe5aa1b34a93491af7516ae6e12fc1d37b28,1611517200
520226,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,eb0413f63ea5928aa27777494d3878a5bc505842,1611267374
520227,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,62161f4a31f82ffedd53d4ac1ee5f554be959442,1611403946
520228,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,77e2fe5aa1b34a93491af7516ae6e12fc1d37b28,1611524302
520229,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,77e2fe5aa1b34a93491af7516ae6e12fc1d37b28,1611517331

In [262]:
article_user

,user_id,article_id,timestamp
0,2bc424123e0a12d29c488bb6e565fe98d0a49b46,e9d06b2bb42bd9970de43beab2d3893534d7a619,1611291180
1,2bc424123e0a12d29c488bb6e565fe98d0a49b46,e98b0d02b16794bc0884a61c4a45746cb9430630,1611290464
2,2bc424123e0a12d29c488bb6e565fe98d0a49b46,05f51c586ada891448ab56d9a5c8adb2a688e2fb,1611406104
3,2bc424123e0a12d29c488bb6e565fe98d0a49b46,91333a3c6d28c9241cbb01678a97699232b79e70,1611531797
4,2bc424123e0a12d29c488bb6e565fe98d0a49b46,30170d08779c54b84170d4cb3b5cbe0462df704a,1611270926
...,...,...,...
520225,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,77e2fe5aa1b34a93491af7516ae6e12fc1d37b28,1611517200
520226,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,eb0413f63ea5928aa27777494d3878a5bc505842,1611267374
520227,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,62161f4a31f82ffedd53d4ac1ee5f554be959442,1611403946
520228,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,77e2fe5aa1b34a93491af7516ae6e12fc1d37b28,1611524302
520229,a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26,77e2fe5aa1b34a93491af7516ae6e12fc1d37b28,1611517331

In [260]:
article_user['user_id'].unique()

array(['2bc424123e0a12d29c488bb6e565fe98d0a49b46',
       'd63acb7f8d2f7478fdea0c9c5a630cca455b0cc3',
       'dae20ce165bd1f86bd762c246df93efc27e16774', ...,
       '585429ca58b381fd348e7085acfe07b25400672b',
       '0141d1c0e8eb74293f08fe83d2ab8849dcbc004a',
       'a5960b8352e6605d3864bfbf39f9d0cf5a3e1d26'], dtype=object)

In [261]:
X_train, X_test, y_train, y_test = train_test_split(article_user, )

ValueError: not enough values to unpack (expected 4, got 2)

In [ ]:
50k users

In [135]:
users = article_user['user_id'].unique()

In [140]:
import numpy as np

In [143]:
len(users)

50000

In [144]:
np.random.choice(users, size=len())

'e30d217014813fd25aa050ff30d0f4a97dd44f40'

In [151]:
article_views = article_user['article_id'].value_counts()#.to_csv('article_counts.csv')

In [164]:
article_views = article_views.to_frame().reset_index()\
        .rename({'article_id': 'article_freq', 'index': 'article_id'}, axis=1)

In [170]:
len(merged['topic'].unique())

36

In [167]:
merged = pd.merge(articles, article_views)

In [233]:
g = merged.groupby('topic')
#g2 = g.apply(lambda x: x.sort_values('article_freq', ascending=False)).nlargest(5, 'article_freq')
#g = merged.groupby('article_id')
g2 = g.apply(lambda x: x.nlargest(5, 'article_freq'))#.nlargest(5, 'article_freq')

In [234]:
g2

                                          article_id  \
topic
africa 257  c701d8085a47cec1b8573e8539c18bdb9d2e84fe
       268  0060ccbcc4bd8683a09a0daa449d31b21dff3095
       290  e27d8c82c3a054995d876b3124acf67207f9b3ef
       523  7d9e568cfc6236287e73e2f3777de6f272abe8af
       234  63c52a666ff4033c8265faaf40ab1f410a87466c
...                                              ...
world  25   889f731b80b1becc703d0f550da3fe85be9251eb
       236  d3810241ac4c40506c1392a189fd67abf0d9baf8
       359  c0587cef8661f800b8f47c8af6520692fd45a1ad
       568  a1981821adab54be5325ee596c350bf3ea0ae370
       227  35a820c34b6623bf91e196cad2b1cf49342ece42

                                                     headline  \
topic
africa 257  Foreign fighters were meant to leave Libya thi...
       268  18-month-old baby under house arrest with Bobi...
       290  Chef arrested after images of sexually suggest...
       523  Nigerian teen jailed for blasphemy has sentenc...
       234  Schools across Africa shutdown as Covid cases ...
...                                                       ...
world  25   Biden's decrees vault America back onto the gl...
       236  Loyal dog waits for six days outside hospital ...
       359  A woman who won a $60 million lottery said she...
       568  Fossil-hunters think they have found the lair ...
       227  A 99-million-year-old beetle shines light on t...

                                                          url  \
topic
africa 257  https://www.cnn.com/2021/01/22/africa/libya-tr...
       268  https://www.cnn.com/2021/01/22/africa/bobi-win...
       290  https://www.cnn.com/2021/01/19/africa/egypt-ar...
       523  https://www.cnn.com/2021/01/22/africa/boy-blas...
       234  https://www.cnn.com/2021/01/24/africa/africa-s...
...                                                       ...
world  25   https://www.cnn.com/2021/01/24/world/us-execut...
       236  https://www.cnn.com/2021/01/22/world/dog-hospi...
       359  https://www.cnn.com/2021/01/24/world/toronto-w...
       568  https://www.cnn.com/2021/01/22/world/giant-wor...
       227  https://www.cnn.com/2021/01/19/world/biolumine...

                       published_date   topic  article_freq
topic
africa 257  2021-01-22 12:57:09.000 Z  africa          1625
       268  2021-01-23 10:00:37.000 Z  africa           780
       290  2021-01-19 18:31:26.000 Z  africa           512
       523  2021-01-22 14:32:17.000 Z  africa           269
       234  2021-01-24 12:59:59.000 Z  africa           139
...                               ...     ...           ...
world  25   2021-01-24 05:12:48.000 Z   world          1518
       236  2021-01-23 02:33:50.000 Z   world          1407
       359  2021-01-25 13:34:41.000 Z   world           464
       568  2021-01-22 18:11:55.000 Z   world           426
       227  2021-01-20 00:01:06.000 Z   world           293

[156 rows x 6 columns]

In [223]:
m = g.apply(lambda x: x.nlargest(5, 'article_freq'))

In [229]:
merged.dtypes

article_id        object
headline          object
url               object
published_date    object
topic             object
article_freq       int64
dtype: object

In [231]:
merged.sort_values(['topic', 'article_freq'], ascending=False)#.groupby('article_id').head(5)

,article_id,headline,url,published_date,topic,article_freq
25,889f731b80b1becc703d0f550da3fe85be9251eb,Biden's decrees vault America back onto the gl...,https://www.cnn.com/2021/01/24/world/us-execut...,2021-01-24 05:12:48.000 Z,world,1518
236,d3810241ac4c40506c1392a189fd67abf0d9baf8,Loyal dog waits for six days outside hospital ...,https://www.cnn.com/2021/01/22/world/dog-hospi...,2021-01-23 02:33:50.000 Z,world,1407
359,c0587cef8661f800b8f47c8af6520692fd45a1ad,A woman who won a $60 million lottery said she...,https://www.cnn.com/2021/01/24/world/toronto-w...,2021-01-25 13:34:41.000 Z,world,464
568,a1981821adab54be5325ee596c350bf3ea0ae370,Fossil-hunters think they have found the lair ...,https://www.cnn.com/2021/01/22/world/giant-wor...,2021-01-22 18:11:55.000 Z,world,426
227,35a820c34b6623bf91e196cad2b1cf49342ece42,A 99-million-year-old beetle shines light on t...,https://www.cnn.com/2021/01/19/world/biolumine...,2021-01-20 00:01:06.000 Z,world,293
...,...,...,...,...,...,...
1137,c256a642e97a5f8ad13e424998f8040b31df6f8c,"If he wins Uganda election, Museveni will work...",https://www.cnn.com/2021/01/13/africa/museveni...,2021-01-13 10:28:51.000 Z,africa,5
769,8e1718f158a66bb469fd4e6e45a26707f663e14b,Uganda's lesson to other authoritarians: contr...,https://www.cnn.com/2021/01/18/africa/uganda-e...,2021-01-18 07:56:31.000 Z,africa,2
1232,fd806175dbf0826bfaab1637a9ecd95339e6ccff,Ugandan presidential candidate Bobi Wine says ...,https://www.cnn.com/2021/01/15/africa/bobi-win...,2021-01-15 16:50:54.000 Z,africa,2
988,7a64f1ea4d2794fd48f7f334e828deadf0725911,How 'African Giant' Burna Boy became a roaring...,https://www.cnn.com/2019/11/21/africa/burna-bo...,2019-11-21 17:58:39.000 Z,africa,1
1198,690d520c941e2073c0f5f46042c34c3d6397ec2f,South African President announces extension of...,https://www.cnn.com/2021/01/11/africa/south-af...,2021-01-12 10:44:07.000 Z,africa,1

In [221]:
m[m['topic'] == 'politics'].nlargest(5, 'article_freq')

,,article_id,headline,url,published_date,topic,article_freq
article_id,,,,,,,
db2c8a1cf0ab92c01b887f12aae94ecaa085861e,55,db2c8a1cf0ab92c01b887f12aae94ecaa085861e,"Trump's last-minute pardons include Bannon, Li...",https://www.cnn.com/2021/01/20/politics/trump-...,2021-01-20 16:22:24.000 Z,politics,9057
a2d1a5acbedba55cabd134677bff8caa98e7472d,76,a2d1a5acbedba55cabd134677bff8caa98e7472d,McConnell privately says he wants Trump gone a...,https://www.cnn.com/2021/01/22/politics/mcconn...,2021-01-23 20:17:12.000 Z,politics,8493
cd032ca6fc83d0c5e46eb85995c36ed91e3726ca,12,cd032ca6fc83d0c5e46eb85995c36ed91e3726ca,Bidens quickly fire White House chief usher in...,https://www.cnn.com/2021/01/20/politics/timoth...,2021-01-21 22:48:10.000 Z,politics,7421
96504e0f0142c2c4334d237344ca64b62aabdacd,39,96504e0f0142c2c4334d237344ca64b62aabdacd,Biden inheriting nonexistent coronavirus vacci...,https://www.cnn.com/2021/01/21/politics/biden-...,2021-01-21 16:37:31.000 Z,politics,7058
30170d08779c54b84170d4cb3b5cbe0462df704a,4,30170d08779c54b84170d4cb3b5cbe0462df704a,Evidence shows Capitol rioters brutally attack...,https://www.cnn.com/2021/01/21/politics/capito...,2021-01-21 12:45:30.000 Z,politics,6511

In [213]:
g2#.to_csv('grouped.csv')

0        714
1       1918
2        101
3       1505
4       6511
        ...
1450       1
1451       1
1452       1
1453       2
1454       1
Name: article_freq, Length: 1455, dtype: int64

In [203]:
g2#.to_csv('grouped.csv')

,,article_id,headline,url,published_date,topic,article_freq
article_id,,,,,,,
001b305991ef92af17c6f3aac436f23e4923d3ad,1142,001b305991ef92af17c6f3aac436f23e4923d3ad,People are calling for museums to be abolished...,https://www.cnn.com/style/article/natural-hist...,2020-07-12 13:12:45.000 Z,style,1
005ea826b0d5d7bff44920ab3bfbe1429da75e37,1028,005ea826b0d5d7bff44920ab3bfbe1429da75e37,National Guardsman holds music classes from th...,https://www.cnn.com/2021/01/18/us/national-gua...,2021-01-23 02:31:22.000 Z,us,10
0060ccbcc4bd8683a09a0daa449d31b21dff3095,268,0060ccbcc4bd8683a09a0daa449d31b21dff3095,18-month-old baby under house arrest with Bobi...,https://www.cnn.com/2021/01/22/africa/bobi-win...,2021-01-23 10:00:37.000 Z,africa,780
007cd607a2fdbc4c698832b98689c5df6c8c46f5,417,007cd607a2fdbc4c698832b98689c5df6c8c46f5,What motivated the Capitol rioters,https://www.cnn.com/2021/01/19/opinions/capito...,2021-01-19 22:22:35.000 Z,opinions,335
0084db47e4dd9a4606fcb7ca1cf9891b65305d58,1077,0084db47e4dd9a4606fcb7ca1cf9891b65305d58,Larry King files for divorce after almost 22 y...,https://www.cnn.com/2019/08/21/entertainment/l...,2019-08-21 12:48:34.000 Z,entertainment,13
...,...,...,...,...,...,...,...
ff8f0085b7a5b1092e5fe97336057d118691a4f0,1354,ff8f0085b7a5b1092e5fe97336057d118691a4f0,"In majority-Black Georgia county, voting in Se...",https://www.cnn.com/2021/01/04/politics/georgi...,2021-01-05 03:04:32.000 Z,politics,2
ffb8c8b023241a724b134c64bda97c1865c75e67,303,ffb8c8b023241a724b134c64bda97c1865c75e67,"If there's anyone who can reach a deal, it's J...",https://www.cnn.com/2021/01/21/opinions/biden-...,2021-01-22 00:46:38.000 Z,opinions,441
ffcf004a9b06edff83d28646cdd176e621f83591,485,ffcf004a9b06edff83d28646cdd176e621f83591,Trumps' snub of Bidens historic in its magnitude,https://www.cnn.com/2021/01/18/politics/trump-...,2021-01-18 21:07:44.000 Z,politics,56
ffddfc7ddf2cd589862b7bcca7dd788eb23f4496,560,ffddfc7ddf2cd589862b7bcca7dd788eb23f4496,Spending more on DoorDash and UberEats? This f...,https://www.cnn.com/2021/01/23/business/doorda...,2021-01-23 19:20:59.000 Z,business,158
ffef0d079dd53e3fc9ecffedab0ab5d0e5782777,569,ffef0d079dd53e3fc9ecffedab0ab5d0e5782777,Guiding gender-atypical kids through puberty,https://www.cnn.com/2021/01/19/health/gender-s...,2021-01-19 16:51:59.000 Z,health,45

In [190]:
merged.sort_values('article_freq', ascending=False)

,article_id,headline,url,published_date,topic,article_freq
55,db2c8a1cf0ab92c01b887f12aae94ecaa085861e,"Trump's last-minute pardons include Bannon, Li...",https://www.cnn.com/2021/01/20/politics/trump-...,2021-01-20 16:22:24.000 Z,politics,9057
76,a2d1a5acbedba55cabd134677bff8caa98e7472d,McConnell privately says he wants Trump gone a...,https://www.cnn.com/2021/01/22/politics/mcconn...,2021-01-23 20:17:12.000 Z,politics,8493
41,438d69f8171684bc46694a4afe17dda8fde280e0,This town powered America for decades. What do...,https://www.cnn.com/2021/01/23/opinions/biden-...,2021-01-23 18:38:50.000 Z,opinions,8002
40,38f29c2a6ab4e5230dc34f6dd79b3e4ef62cac17,The face mask that could end the pandemic,https://www.cnn.com/2021/01/22/health/face-mas...,2021-01-23 15:24:09.000 Z,health,7940
96,590310995f40447205e51d908264faedd575ad20,"Larry King, legendary talk show host, dies at 87",https://www.cnn.com/2021/01/23/us/larry-king-d...,2021-01-24 12:07:33.000 Z,us,7529
...,...,...,...,...,...,...
1310,84dcda0ea8d6e5c926f8022c72b6cc2c8e61bcb4,US Postal Service removing mailboxes for secur...,https://www.cnn.com/2021/01/16/us/us-postal-se...,2021-01-16 23:39:44.000 Z,us,1
1312,62ee316b0c45150fd96fbda169a112f33e27e69c,Pentagon and DC officials trade barbs over han...,https://www.cnn.com/2021/01/09/politics/nation...,2021-01-09 12:50:57.000 Z,politics,1
1314,0eb560ba233979bf30cb82f9ae3f1a37a3342369,What's gone wrong at Ferrari and can Formula O...,https://www.cnn.com/2020/12/14/motorsport/form...,2020-12-15 09:42:22.000 Z,motorsport,1
1318,55b48ffbbe478b3e378ebd7aee515dcd48693db3,Uyghurs are desperate for action in Xinjiang. ...,https://www.cnn.com/2020/10/26/asia/trump-bide...,2020-10-27 04:14:49.000 Z,asia,1
1454,146a051187867c1f5592ea278999adf6017d68a9,"Before Wednesday, insurgents waving Confederat...",https://www.cnn.com/2021/01/07/us/capitol-conf...,2021-01-07 19:44:59.000 Z,us,1

In [235]:
from datetime import date, timedelta

In [236]:
date

datetime.date

In [239]:
date.today() - timedelta(days=7)

datetime.date(2021, 3, 29)

In [244]:
m['published_date'] = pd.to_datetime(m['published_date'])

In [245]:
m[m['published_date'] > date.today()]

TypeError: Invalid comparison between dtype=datetime64[ns, UTC] and date

In [ ]:
m[m['']]